# Generated by Django 4.2.2 on 2023-06-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_quesion_choice_qusition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesion',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
