# Generated by Django 4.2.2 on 2023-06-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_rename_lesson_id_quesion_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesion',
            old_name='lesson',
            new_name='lesson_id',
        ),
    ]
