# Generated by Django 4.2.2 on 2023-06-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_rename_lesson_quesion_lesson_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quesion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='qusition_id',
            new_name='question_id',
        ),
    ]
