# Generated by Django 4.2.2 on 2023-06-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_alter_question_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
    ]
